name: "Terraform CI Github Actions Workflow"
on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

      actions:
        description: 'Actions to perform'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform action flick!!"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v6

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: "Terraform Init"
        run: terraform init

      - name: select or create workspace
        run:  terraform workspace select -or-create ${{ github.event.inputs.target_environment }} 
      
      - name: terraform format check
        run: terraform fmt -check

      - name: terraform plan
        if: ${{ github.event.inputs.actions == 'plan' || github.event.inputs.actions == 'apply' }}
        run: terraform plan -var-file="${{ github.event.inputs.target_environment }}.tfvars" -no-color

      - name: terraform apply
        if: ${{ github.event.inputs.actions == 'apply' }}
        run: terraform apply -var-file="${{ github.event.inputs.target_environment }}.tfvars" -auto-approve

      - name: terraform destroy
        if: ${{ github.event.inputs.actions == 'destroy' }}
        run: terraform destroy -var-file="${{ github.event.inputs.target_environment }}.tfvars" -auto-approve